name: Debug Workflow

on:
  push:
    branches: 
      - main
 

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug env
        run: |
          echo "BRANCH: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"

      - name: Install deps 
        run: npm ci --verbose

      - name: Test job
        run: |
          echo "Running test..."
          echo "Event payload: $github.event.head_commit.message"

      - name: Upload log
        uses: actions/upload-artifact@v2
        if: failure()
        with: 
          name: logs
          path: logs

      - name: Manual trigger
        run: echo "Manually triggered!"
        if: github.event_name == 'workflow_dispatch'