name: Matrix Demo
on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
     
    build:
        continue-on-error: true
        strategy:
         matrix:
            node-version: [12,14,16]
            operating-system: [ubuntu-latest,windows-latest]
            include: 
                - node-verion: 18
                  operating-system: ubuntu-latest
            exclude:
                - node-verion: 12
                  operating-system: windows-latest
        runs-on: ${{matrix.operating-system}}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-verion}}
            - name: Install Dependency
              run: npm ci
            - name: Build project
              run: npm run build
